[package]
name = "username-anda/sekolah-app"
version = "0.1.0"
description = "Aplikasi Sekolah Django"

[[command]]
name = "web"
runner = "https://webc.org/runner/python"
annotations = {
  wasi = {
    env = ["PYTHONPATH=/app"]
  }
}

[app]
exec = "python -m gunicorn nama_folder_project.wsgi:application --bind 0.0.0.0:$PORT"
